apiVersion: v1
kind: Namespace
metadata:
  name: prj-example-1
  annotations:
    cardano.demeter.run/network: preview
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demeter-config
  namespace: prj-example-1
data:
  name: example-1
  slug: example-1
  status: active
---
apiVersion: demeter.run/v1alpha1
kind: Frontend
metadata:
  name: foo
  namespace: prj-example-1
spec:
  annotations:
    cardano.demeter.run/network: preview
  args: ""
  command: ""
  computeClass: gp1.x86.nano
  config: []
  enabled: true
  envVars: []
  givenName: TxPipe Website
  image: ghcr.io/txpipe/website:1e4991796bc9fb55718a7b0cfcb37617d56bf9e5
  replicas: 1
